export { AttorneyProfiles } from './components/attorney-profiles'
export type { Attorney } from './components/attorney-profiles'
export { PracticeAreas } from './components/practice-areas'
export type { PracticeArea } from './components/practice-areas'
export { ConsultationBooking } from './components/consultation-booking'
export type { ConsultationBookingData } from './components/consultation-booking'
export { LawyerDirectory } from './components/lawyer-directory'
export type { Lawyer } from './components/lawyer-directory'
export { CaseEvaluator } from './components/case-evaluator'
export type { CaseEvaluatorData } from './components/case-evaluator'
export { PracticeAreasGrid } from './components/practice-areas-grid'
export type { PracticeAreaCard } from './components/practice-areas-grid'
