import type { MetadataRoute } from 'next'

const BASE_URL = 'https://sites.get-scala.com'

// Keep in sync with the `verticals` registry in app/page.tsx — only the
// public template gallery is indexed. Named client-demo routes (labrace,
// immobilcapital, rse-tenderos, costruzioni, ...) are intentionally left
// out: they're unlinked-by-design and only shared via direct URL.
const PUBLIC_SLUGS = [
  '/restaurant',
  '/restaurant-modern',
  '/pizzeria',
  '/cafe',
  '/bakery',
  '/gelateria',
  '/sushi',
  '/winebar',
  '/brewery',
  '/butcher',
  '/catering',
  '/property',
  '/property-luxury',
  '/hotel',
  '/hotel-boutique',
  '/bnb',
  '/coworking',
  '/marina',
  '/camping',
  '/beauty',
  '/beauty-spa',
  '/barber',
  '/tattoo',
  '/gym',
  '/gym-crossfit',
  '/yoga',
  '/nutritionist',
  '/physiotherapy',
  '/psychologist',
  '/dermaly',
  '/dermaly-skin',
  '/chiropractor',
  '/clinic',
  '/clinic-dental',
  '/optician',
  '/pharmacy',
  '/vet',
  '/vet-exotic',
  '/pet-shop',
  '/photographer',
  '/studio',
  '/studio-architecture',
  '/interior-designer',
  '/art-gallery',
  '/jeweler',
  '/dj',
  '/event-planner',
  '/agency',
  '/agency-creative',
  '/law',
  '/law-ip',
  '/notary',
  '/accountant',
  '/accountant-startup',
  '/financial-advisor',
  '/insurance',
  '/consulting',
  '/recruitment',
  '/it-services',
  '/printing',
  '/school',
  '/school-music',
  '/tutoring',
  '/daycare',
  '/driving-school',
  '/surf-school',
  '/dance-school',
  '/auto',
  '/dealership',
  '/car-rental',
  '/car-wash',
  '/electrician',
  '/plumber',
  '/painter',
  '/roofing',
  '/landscaping',
  '/pool-service',
  '/pest-control',
  '/moving',
  '/clean',
  '/clean-commercial',
  '/laundry',
  '/tailor',
  '/bowling',
  '/cinema',
  '/escape-room',
  '/wedding',
  '/wedding-barn',
  '/travel-agency',
  '/tour-guide',
  '/bike-shop',
  '/bookstore',
  '/shop',
  '/shop-local',
  '/florist',
  '/farm-shop',
  '/vineyard',
  '/church',
  '/nonprofit',
]

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()

  return [
    {
      url: BASE_URL,
      lastModified: now,
      changeFrequency: 'weekly',
      priority: 1.0,
    },
    {
      url: `${BASE_URL}/pricing`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    ...PUBLIC_SLUGS.map((slug) => ({
      url: `${BASE_URL}${slug}`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.6,
    })),
  ]
}
