export type Category =
  | 'All'
  | 'Food & Drink'
  | 'Property'
  | 'Health & Beauty'
  | 'Creative'
  | 'Professional Services'
  | 'Education'
  | 'Automotive'
  | 'Entertainment'
  | 'Home Services'
  | 'Travel'
  | 'Retail'
  | 'Community'

export interface Vertical {
  name: string
  slug: string
  tagline: string
  color: string
  colorEnd: string
  category: Category
  icon: string
}

export const verticals: Vertical[] = [
  // ── Food & Drink ──────────────────────────────────────────────────────────
  {
    name: 'DineOS',
    slug: '/restaurant',
    tagline: 'Classic restaurant with bookings & menu',
    color: '#78350f',
    colorEnd: '#b45309',
    category: 'Food & Drink',
    icon: '🍽',
  },
  {
    name: 'DineOS — Modern',
    slug: '/restaurant-modern',
    tagline: 'Contemporary Japanese, dark minimalist',
    color: '#18181b',
    colorEnd: '#e8c547',
    category: 'Food & Drink',
    icon: '🍣',
  },
  {
    name: 'PizzaOS',
    slug: '/pizzeria',
    tagline: 'Neapolitan pizzeria, order & delivery',
    color: '#b91c1c',
    colorEnd: '#dc7f2a',
    category: 'Food & Drink',
    icon: '🍕',
  },
  {
    name: 'CaféOS',
    slug: '/cafe',
    tagline: 'Specialty coffee & brunch café',
    color: '#3b2005',
    colorEnd: '#92400e',
    category: 'Food & Drink',
    icon: '☕',
  },
  {
    name: 'BakeryOS',
    slug: '/bakery',
    tagline: 'Artisan bakery, sourdough & patisserie',
    color: '#7c2d12',
    colorEnd: '#c2410c',
    category: 'Food & Drink',
    icon: '🍞',
  },
  {
    name: 'GelateriaOS',
    slug: '/gelateria',
    tagline: 'Artisan gelato & dessert parlour',
    color: '#701a75',
    colorEnd: '#db2777',
    category: 'Food & Drink',
    icon: '🍦',
  },
  {
    name: 'SushiOS',
    slug: '/sushi',
    tagline: 'Modern Japanese sushi restaurant',
    color: '#0f172a',
    colorEnd: '#dc2626',
    category: 'Food & Drink',
    icon: '🍱',
  },
  {
    name: 'BreweryOS',
    slug: '/brewery',
    tagline: 'Craft brewery & taproom experience',
    color: '#1c1202',
    colorEnd: '#d97706',
    category: 'Food & Drink',
    icon: '🍺',
  },
  {
    name: 'WineBarOS',
    slug: '/winebar',
    tagline: 'Natural wine bar & small plates',
    color: '#4c0519',
    colorEnd: '#9f1239',
    category: 'Food & Drink',
    icon: '🍷',
  },
  {
    name: 'FarmOS',
    slug: '/farm-shop',
    tagline: 'Organic farm shop & weekly veg boxes',
    color: '#4a6218',
    colorEnd: '#8b6914',
    category: 'Food & Drink',
    icon: '🌿',
  },
  {
    name: 'ButcherOS',
    slug: '/butcher',
    tagline: 'Traditional family butchers since 1954',
    color: '#3c1f0a',
    colorEnd: '#8b0000',
    category: 'Food & Drink',
    icon: '🥩',
  },
  {
    name: 'VineyardOS',
    slug: '/vineyard',
    tagline: 'Estate winery, tours & tastings',
    color: '#4a1942',
    colorEnd: '#c9a84c',
    category: 'Food & Drink',
    icon: '🍇',
  },
  {
    name: 'CateringOS',
    slug: '/catering',
    tagline: 'Event catering & private dining',
    color: '#14532d',
    colorEnd: '#059669',
    category: 'Food & Drink',
    icon: '🍴',
  },
  // ── Property ──────────────────────────────────────────────────────────────
  {
    name: 'PropertyOS',
    slug: '/property',
    tagline: 'Real estate agency with listings & valuations',
    color: '#1e3a5f',
    colorEnd: '#2563eb',
    category: 'Property',
    icon: '🏠',
  },
  {
    name: 'PropertyOS — Luxury',
    slug: '/property-luxury',
    tagline: 'Ultra-prime & luxury real estate',
    color: '#1a1200',
    colorEnd: '#c9a84c',
    category: 'Property',
    icon: '🏛',
  },
  {
    name: 'TravelOS',
    slug: '/hotel',
    tagline: 'Hotel, B&B, resort — full availability',
    color: '#0f172a',
    colorEnd: '#1e40af',
    category: 'Property',
    icon: '🏨',
  },
  {
    name: 'TravelOS — Boutique',
    slug: '/hotel-boutique',
    tagline: 'Boutique hotel & spa, Cotswolds warmth',
    color: '#2c1a0e',
    colorEnd: '#7c5e4a',
    category: 'Property',
    icon: '🌿',
  },
  {
    name: 'BnBOS',
    slug: '/bnb',
    tagline: 'Bed & breakfast, host-led experience',
    color: '#1e2832',
    colorEnd: '#4f6f8f',
    category: 'Property',
    icon: '🛏',
  },
  {
    name: 'CoworkOS',
    slug: '/coworking',
    tagline: 'Coworking space, desks & meeting rooms',
    color: '#1e1b4b',
    colorEnd: '#6d28d9',
    category: 'Property',
    icon: '🖥',
  },
  {
    name: 'MarinaOS',
    slug: '/marina',
    tagline: 'Marina & boat berth management',
    color: '#0c1a2e',
    colorEnd: '#0369a1',
    category: 'Property',
    icon: '⛵',
  },
  // ── Health & Beauty ───────────────────────────────────────────────────────
  {
    name: 'BeautyOS',
    slug: '/beauty',
    tagline: 'Hair salon, spa, barber — book online',
    color: '#6b0f2f',
    colorEnd: '#e11d48',
    category: 'Health & Beauty',
    icon: '💇',
  },
  {
    name: 'BeautyOS — Spa',
    slug: '/beauty-spa',
    tagline: 'Luxury day spa & wellness sanctuary',
    color: '#3d2b24',
    colorEnd: '#a07860',
    category: 'Health & Beauty',
    icon: '🌸',
  },
  {
    name: 'BarberOS',
    slug: '/barber',
    tagline: 'Premium barbershop with booking & loyalty',
    color: '#1c1c1c',
    colorEnd: '#b45309',
    category: 'Health & Beauty',
    icon: '✂',
  },
  {
    name: 'GymOS',
    slug: '/gym',
    tagline: 'Gym & fitness studio, class scheduling',
    color: '#18181b',
    colorEnd: '#3f3f46',
    category: 'Health & Beauty',
    icon: '🏋',
  },
  {
    name: 'GymOS — CrossFit',
    slug: '/gym-crossfit',
    tagline: 'CrossFit box, bold high-intensity brand',
    color: '#1a0000',
    colorEnd: '#cc2200',
    category: 'Health & Beauty',
    icon: '🔥',
  },
  {
    name: 'YogaOS',
    slug: '/yoga',
    tagline: 'Yoga studio, classes & retreats',
    color: '#2d1654',
    colorEnd: '#7c3aed',
    category: 'Health & Beauty',
    icon: '🧘',
  },
  {
    name: 'ClinicoOS',
    slug: '/clinic',
    tagline: 'Medical clinic with appointments & records',
    color: '#042f2e',
    colorEnd: '#0d9488',
    category: 'Health & Beauty',
    icon: '🏥',
  },
  {
    name: 'PraxisOS — Dental',
    slug: '/clinic-dental',
    tagline: 'Modern dental practice, conversion-focused',
    color: '#023e6e',
    colorEnd: '#0077b6',
    category: 'Health & Beauty',
    icon: '🦷',
  },
  {
    name: 'DermalyOS',
    slug: '/dermaly',
    tagline: 'Luxury dermatology clinic, Harley Street',
    color: '#3d1a22',
    colorEnd: '#b76e79',
    category: 'Health & Beauty',
    icon: '💉',
  },
  {
    name: 'DermalyOS — Skin',
    slug: '/dermaly-skin',
    tagline: 'Accessible skincare clinic, Shoreditch',
    color: '#2c1a12',
    colorEnd: '#9a6652',
    category: 'Health & Beauty',
    icon: '✨',
  },
  {
    name: 'PetOS',
    slug: '/vet',
    tagline: 'Veterinary clinic, pet care & grooming',
    color: '#052e16',
    colorEnd: '#16a34a',
    category: 'Health & Beauty',
    icon: '🐾',
  },
  {
    name: 'PetOS — Exotic',
    slug: '/vet-exotic',
    tagline: 'Exotic & small animal specialists',
    color: '#0a2318',
    colorEnd: '#2d6a4f',
    category: 'Health & Beauty',
    icon: '🦎',
  },
  {
    name: 'NutritionOS',
    slug: '/nutritionist',
    tagline: 'Nutritionist & dietitian consultations',
    color: '#14532d',
    colorEnd: '#4ade80',
    category: 'Health & Beauty',
    icon: '🥗',
  },
  {
    name: 'PhysioOS',
    slug: '/physiotherapy',
    tagline: 'Physiotherapy & sports rehab clinic',
    color: '#1e3a5f',
    colorEnd: '#38bdf8',
    category: 'Health & Beauty',
    icon: '🦾',
  },
  {
    name: 'ChiroOS',
    slug: '/chiropractor',
    tagline: 'Chiropractic clinic, spinal & joint care',
    color: '#1a2e4a',
    colorEnd: '#3b82f6',
    category: 'Health & Beauty',
    icon: '🦴',
  },
  {
    name: 'PsychoOS',
    slug: '/psychologist',
    tagline: 'Psychology & therapy, online & in-person',
    color: '#1e1b4b',
    colorEnd: '#818cf8',
    category: 'Health & Beauty',
    icon: '🧠',
  },
  {
    name: 'OpticOS',
    slug: '/optician',
    tagline: 'Optician & eyewear boutique',
    color: '#0c1a2e',
    colorEnd: '#06b6d4',
    category: 'Health & Beauty',
    icon: '👓',
  },
  {
    name: 'PharmaOS',
    slug: '/pharmacy',
    tagline: 'Independent pharmacy & health products',
    color: '#042f2e',
    colorEnd: '#0f766e',
    category: 'Health & Beauty',
    icon: '💊',
  },
  // ── Creative ──────────────────────────────────────────────────────────────
  {
    name: 'StudioOS',
    slug: '/studio',
    tagline: 'Creative studio, portfolio & project intake',
    color: '#111111',
    colorEnd: '#52525b',
    category: 'Creative',
    icon: '🎨',
  },
  {
    name: 'StudioOS — Architecture',
    slug: '/studio-architecture',
    tagline: 'Architecture & interior design, Clerkenwell',
    color: '#1c1917',
    colorEnd: '#b8a898',
    category: 'Creative',
    icon: '🏛',
  },
  {
    name: 'AgencyOS',
    slug: '/agency',
    tagline: 'Performance marketing & brand strategy',
    color: '#1e1b4b',
    colorEnd: '#6c63ff',
    category: 'Creative',
    icon: '📈',
  },
  {
    name: 'AgencyOS — Creative',
    slug: '/agency-creative',
    tagline: 'Brand & content agency, Fitzrovia',
    color: '#0a0a0a',
    colorEnd: '#6d28d9',
    category: 'Creative',
    icon: '✦',
  },
  {
    name: 'WeddingOS',
    slug: '/wedding',
    tagline: 'Wedding venue & planner, full showcase',
    color: '#4a0a28',
    colorEnd: '#be185d',
    category: 'Creative',
    icon: '💒',
  },
  {
    name: 'WeddingOS — Barn',
    slug: '/wedding-barn',
    tagline: 'Rustic barn venue, Hampshire countryside',
    color: '#2c1e12',
    colorEnd: '#92705a',
    category: 'Creative',
    icon: '🌾',
  },
  {
    name: 'EventOS',
    slug: '/event-planner',
    tagline: 'Event planner & production company',
    color: '#1a0a2e',
    colorEnd: '#9333ea',
    category: 'Creative',
    icon: '🎪',
  },
  {
    name: 'PhotographerOS',
    slug: '/photographer',
    tagline: 'Photography portfolio with booking & prints',
    color: '#1a1a2e',
    colorEnd: '#7c3aed',
    category: 'Creative',
    icon: '📷',
  },
  {
    name: 'TattooOS',
    slug: '/tattoo',
    tagline: 'Tattoo studio & piercing, book artists',
    color: '#0a0a0a',
    colorEnd: '#dc2626',
    category: 'Creative',
    icon: '🖋',
  },
  {
    name: 'DanceOS',
    slug: '/dance-school',
    tagline: 'Dance school — classes for all levels',
    color: '#1e0a2e',
    colorEnd: '#ec4899',
    category: 'Creative',
    icon: '💃',
  },
  {
    name: 'DJOS',
    slug: '/dj',
    tagline: 'DJ & music producer — bookings & mixes',
    color: '#0a0a14',
    colorEnd: '#6c63ff',
    category: 'Creative',
    icon: '🎧',
  },
  {
    name: 'InteriorOS',
    slug: '/interior-designer',
    tagline: 'Interior design studio & consultancy',
    color: '#1c1410',
    colorEnd: '#d4a96a',
    category: 'Creative',
    icon: '🛋',
  },
  {
    name: 'GalleryOS',
    slug: '/art-gallery',
    tagline: 'Contemporary art gallery & exhibitions',
    color: '#1a1a1a',
    colorEnd: '#e11d48',
    category: 'Creative',
    icon: '🖼',
  },
  // ── Professional Services ─────────────────────────────────────────────────
  {
    name: 'LegalOS',
    slug: '/law',
    tagline: 'Law firm, solicitors — trust & authority',
    color: '#0f0f2e',
    colorEnd: '#3730a3',
    category: 'Professional Services',
    icon: '⚖',
  },
  {
    name: 'LegalOS — IP',
    slug: '/law-ip',
    tagline: 'Intellectual property law firm, Holborn',
    color: '#0b1e2d',
    colorEnd: '#1b3a4b',
    category: 'Professional Services',
    icon: '™',
  },
  {
    name: 'AccountantOS',
    slug: '/accountant',
    tagline: 'Chartered accountants, Canary Wharf',
    color: '#0d1f3c',
    colorEnd: '#1e3a5f',
    category: 'Professional Services',
    icon: '📒',
  },
  {
    name: 'AccountantOS — Startup',
    slug: '/accountant-startup',
    tagline: 'Accountants for startups & freelancers',
    color: '#00374a',
    colorEnd: '#00b4d8',
    category: 'Professional Services',
    icon: '🚀',
  },
  {
    name: 'InsuranceOS',
    slug: '/insurance',
    tagline: 'Independent insurance broker & advisor',
    color: '#0f1e3c',
    colorEnd: '#2563eb',
    category: 'Professional Services',
    icon: '🛡',
  },
  {
    name: 'FinanceOS',
    slug: '/financial-advisor',
    tagline: 'Financial planning & wealth management',
    color: '#0a1628',
    colorEnd: '#1d4ed8',
    category: 'Professional Services',
    icon: '💰',
  },
  {
    name: 'ConsultingOS',
    slug: '/consulting',
    tagline: 'Management consulting & strategy',
    color: '#0f1e3c',
    colorEnd: '#3730a3',
    category: 'Professional Services',
    icon: '📊',
  },
  {
    name: 'RecruitOS',
    slug: '/recruitment',
    tagline: 'Recruitment agency & talent search',
    color: '#1a1028',
    colorEnd: '#7c3aed',
    category: 'Professional Services',
    icon: '👔',
  },
  {
    name: 'NotaryOS',
    slug: '/notary',
    tagline: 'Notary public & document services',
    color: '#1a1a2e',
    colorEnd: '#4338ca',
    category: 'Professional Services',
    icon: '📜',
  },
  {
    name: 'ITServOS',
    slug: '/it-services',
    tagline: 'IT support, cybersecurity & managed services',
    color: '#0a1420',
    colorEnd: '#0ea5e9',
    category: 'Professional Services',
    icon: '💻',
  },
  {
    name: 'PrintOS',
    slug: '/printing',
    tagline: 'Commercial printing & signage studio',
    color: '#0a1428',
    colorEnd: '#1d4ed8',
    category: 'Professional Services',
    icon: '🖨',
  },
  {
    name: 'MovingOS',
    slug: '/moving',
    tagline: 'Removal company & storage services',
    color: '#1c1408',
    colorEnd: '#d97706',
    category: 'Professional Services',
    icon: '🚚',
  },
  {
    name: 'TailorOS',
    slug: '/tailor',
    tagline: 'Bespoke tailoring & alterations',
    color: '#1a1210',
    colorEnd: '#92400e',
    category: 'Professional Services',
    icon: '🧵',
  },
  // ── Education ─────────────────────────────────────────────────────────────
  {
    name: 'EduOS',
    slug: '/school',
    tagline: 'School, academy & online courses',
    color: '#2e1065',
    colorEnd: '#7c3aed',
    category: 'Education',
    icon: '🎓',
  },
  {
    name: 'EduOS — Music',
    slug: '/school-music',
    tagline: 'Music academy, learn any instrument',
    color: '#12121f',
    colorEnd: '#6366f1',
    category: 'Education',
    icon: '🎸',
  },
  {
    name: 'DaycareOS',
    slug: '/daycare',
    tagline: 'Childcare & nursery, parent reassurance',
    color: '#0c2a00',
    colorEnd: '#65a30d',
    category: 'Education',
    icon: '🧒',
  },
  {
    name: 'TutoringOS',
    slug: '/tutoring',
    tagline: 'Private tutoring & exam preparation',
    color: '#1e1b4b',
    colorEnd: '#a855f7',
    category: 'Education',
    icon: '📐',
  },
  {
    name: 'DrivingOS',
    slug: '/driving-school',
    tagline: 'Driving school — theory & practical lessons',
    color: '#1a1800',
    colorEnd: '#ca8a04',
    category: 'Education',
    icon: '🚘',
  },
  {
    name: 'SurfOS',
    slug: '/surf-school',
    tagline: 'Surf school & ocean sports academy',
    color: '#0c2240',
    colorEnd: '#0ea5e9',
    category: 'Education',
    icon: '🏄',
  },
  // ── Automotive ────────────────────────────────────────────────────────────
  {
    name: 'AutoOS',
    slug: '/auto',
    tagline: 'Car dealership, garage & servicing',
    color: '#111111',
    colorEnd: '#3f3f46',
    category: 'Automotive',
    icon: '🚗',
  },
  {
    name: 'MotorOS — Dealership',
    slug: '/dealership',
    tagline: 'Certified pre-owned dealership, East London',
    color: '#1a0000',
    colorEnd: '#e63946',
    category: 'Automotive',
    icon: '🚘',
  },
  {
    name: 'CarRentalOS',
    slug: '/car-rental',
    tagline: 'Car rental & fleet management',
    color: '#0c1620',
    colorEnd: '#0369a1',
    category: 'Automotive',
    icon: '🔑',
  },
  {
    name: 'CarWashOS',
    slug: '/car-wash',
    tagline: 'Premium car wash & detailing studio',
    color: '#0a1428',
    colorEnd: '#2563eb',
    category: 'Automotive',
    icon: '✨',
  },
  {
    name: 'BikeOS',
    slug: '/bike-shop',
    tagline: 'Bicycle shop, repair & custom builds',
    color: '#1a2810',
    colorEnd: '#65a30d',
    category: 'Automotive',
    icon: '🚲',
  },
  // ── Entertainment ─────────────────────────────────────────────────────────
  {
    name: 'CinemaOS',
    slug: '/cinema',
    tagline: 'Independent cinema, showtimes & events',
    color: '#0a0a14',
    colorEnd: '#dc2626',
    category: 'Entertainment',
    icon: '🎬',
  },
  {
    name: 'EscapeOS',
    slug: '/escape-room',
    tagline: 'Escape room experience & team bookings',
    color: '#0a0a0a',
    colorEnd: '#7c3aed',
    category: 'Entertainment',
    icon: '🔐',
  },
  {
    name: 'BowlingOS',
    slug: '/bowling',
    tagline: 'Bowling alley, lanes & party packages',
    color: '#1a0820',
    colorEnd: '#9333ea',
    category: 'Entertainment',
    icon: '🎳',
  },
  {
    name: 'CampingOS',
    slug: '/camping',
    tagline: 'Campsite & glamping — pitch booking',
    color: '#0a2010',
    colorEnd: '#16a34a',
    category: 'Entertainment',
    icon: '⛺',
  },
  {
    name: 'TravelAgencyOS',
    slug: '/travel-agency',
    tagline: 'Travel agency — bespoke & group trips',
    color: '#0a1428',
    colorEnd: '#0ea5e9',
    category: 'Travel',
    icon: '✈',
  },
  {
    name: 'TourOS',
    slug: '/tour-guide',
    tagline: 'Tour guide & local experiences',
    color: '#1a2810',
    colorEnd: '#84cc16',
    category: 'Travel',
    icon: '🗺',
  },
  // ── Home Services ─────────────────────────────────────────────────────────
  {
    name: 'CleanOS',
    slug: '/clean',
    tagline: 'Luxury home cleaning, Knightsbridge',
    color: '#0c2233',
    colorEnd: '#1a5276',
    category: 'Home Services',
    icon: '🧹',
  },
  {
    name: 'CleanOS — Commercial',
    slug: '/clean-commercial',
    tagline: 'B2B contract cleaning, City of London',
    color: '#050d14',
    colorEnd: '#1e4976',
    category: 'Home Services',
    icon: '🏢',
  },
  {
    name: 'PlumberOS',
    slug: '/plumber',
    tagline: 'Emergency plumbing & heating, local trust',
    color: '#0a1628',
    colorEnd: '#2563eb',
    category: 'Home Services',
    icon: '🔧',
  },
  {
    name: 'ElectricOS',
    slug: '/electrician',
    tagline: 'Electrician & electrical services',
    color: '#14100a',
    colorEnd: '#eab308',
    category: 'Home Services',
    icon: '⚡',
  },
  {
    name: 'PainterOS',
    slug: '/painter',
    tagline: 'Painters & decorators, residential & commercial',
    color: '#1a1228',
    colorEnd: '#a855f7',
    category: 'Home Services',
    icon: '🎨',
  },
  {
    name: 'RoofingOS',
    slug: '/roofing',
    tagline: 'Roofing contractor, repair & replacement',
    color: '#1a1010',
    colorEnd: '#dc2626',
    category: 'Home Services',
    icon: '🏠',
  },
  {
    name: 'LandscapeOS',
    slug: '/landscaping',
    tagline: 'Landscaping, garden design & maintenance',
    color: '#0a1e08',
    colorEnd: '#16a34a',
    category: 'Home Services',
    icon: '🌳',
  },
  {
    name: 'PoolOS',
    slug: '/pool-service',
    tagline: 'Swimming pool installation & maintenance',
    color: '#0a1e38',
    colorEnd: '#0ea5e9',
    category: 'Home Services',
    icon: '🏊',
  },
  {
    name: 'PestOS',
    slug: '/pest-control',
    tagline: 'Pest control & extermination services',
    color: '#0a1a0a',
    colorEnd: '#4d7c0f',
    category: 'Home Services',
    icon: '🐛',
  },
  {
    name: 'LaundryOS',
    slug: '/laundry',
    tagline: 'Laundry & dry cleaning collection',
    color: '#0c1e38',
    colorEnd: '#0369a1',
    category: 'Home Services',
    icon: '👕',
  },
  // ── Retail ────────────────────────────────────────────────────────────────
  {
    name: 'ShopOS',
    slug: '/shop',
    tagline: 'Luxury fashion & lifestyle boutique',
    color: '#1c1410',
    colorEnd: '#c8956c',
    category: 'Retail',
    icon: '🛍',
  },
  {
    name: 'ShopOS — Local',
    slug: '/shop-local',
    tagline: 'Artisan grocery & deli, conversion-first',
    color: '#0f2008',
    colorEnd: '#4ade80',
    category: 'Retail',
    icon: '🥦',
  },
  {
    name: 'BookOS',
    slug: '/bookstore',
    tagline: 'Independent bookshop & events programme',
    color: '#1a1410',
    colorEnd: '#a16207',
    category: 'Retail',
    icon: '📚',
  },
  {
    name: 'PetShopOS',
    slug: '/pet-shop',
    tagline: 'Pet shop, food & accessories',
    color: '#0a2010',
    colorEnd: '#16a34a',
    category: 'Retail',
    icon: '🐶',
  },
  {
    name: 'JewelOS',
    slug: '/jeweler',
    tagline: 'Jeweller — bespoke & luxury pieces',
    color: '#1a1200',
    colorEnd: '#d4af37',
    category: 'Retail',
    icon: '💎',
  },
  {
    name: 'FloristOS',
    slug: '/florist',
    tagline: 'Florist — bouquets, events & subscriptions',
    color: '#1a0a28',
    colorEnd: '#ec4899',
    category: 'Retail',
    icon: '💐',
  },
  // ── Community ─────────────────────────────────────────────────────────────
  {
    name: 'NonprofitOS',
    slug: '/nonprofit',
    tagline: 'Charity & nonprofit — donate & volunteer',
    color: '#b45309',
    colorEnd: '#dc2626',
    category: 'Community',
    icon: '❤',
  },
  {
    name: 'ChurchOS',
    slug: '/church',
    tagline: 'Community church — services & ministries',
    color: '#4a1942',
    colorEnd: '#b5942a',
    category: 'Community',
    icon: '✝',
  },
]

export const CATEGORIES: Category[] = [
  'All',
  'Food & Drink',
  'Property',
  'Health & Beauty',
  'Creative',
  'Professional Services',
  'Education',
  'Automotive',
  'Entertainment',
  'Home Services',
  'Travel',
  'Retail',
  'Community',
]
